CREATE DATABASE CAPAS
SHOW VARIABLES LIKE 'datadir';

DROP TABLE emergencia, infraestructura, sanitario_ecologico;

CREATE TABLE EMERGENCIA (
	ID_EMERGENCIA INT NOT NULL,
	FENOMENO VARCHAR(100) NOT NULL,
	TAXONOMIA VARCHAR(100) NULL,
	RPVE VARCHAR(100) NOT NULL,
	INTENSIDAD VARCHAR(100) NULL,
	DESCRIPCION VARCHAR(100) NOT NULL,
	DETALLES VARCHAR(300) NULL,
	NOMBRE VARCHAR(100) NULL,
	FUENTE VARCHAR(300) NOT NULL,
	MAGNI_UNI VARCHAR(100) NULL,
	MAGNI_NUM VARCHAR(100) NULL,
	CALLE VARCHAR(300) NOT NULL,
	NUMERO VARCHAR(100) NOT NULL,
	COLONIA VARCHAR(100) NOT NULL,
	CVE_MUN INT NOT NULL,
	ALCALDIA VARCHAR(50) NOT NULL,
	ENTIDAD VARCHAR(50) NOT NULL,
	LATITUD FLOAT NOT NULL,
	LONGITUD FLOAT NOT NULL,
	CONSTRAINT PK_EMERGENCIA PRIMARY KEY (ID_EMERGENCIA)
);

CREATE TABLE SANITARIO_ECOLOGICO(
	ID_SANITARIO INT NOT NULL,
	FENOMENO VARCHAR(100) NOT NULL,
	TAXONOMIA VARCHAR(100) NULL,
	RPVE VARCHAR(100) NOT NULL,
	INTENSIDAD VARCHAR(100) NULL,
	DESCRIPCION VARCHAR(100) NOT NULL,
	DETALLES VARCHAR(300) NULL,
	NOMBRE VARCHAR(100) NULL,
	FUENTE VARCHAR(300) NOT NULL,
	MAGNI_UNI VARCHAR(100) NULL,
	MAGNI_NUM VARCHAR(100) NULL,
	CALLE VARCHAR(300) NOT NULL,
	NUMERO VARCHAR(100) NOT NULL,
	COLONIA VARCHAR(100) NOT NULL,
	CVE_MUN INT NOT NULL,
	ALCALDIA VARCHAR(50) NOT NULL,
	ENTIDAD VARCHAR(50) NOT NULL,
	LATITUD FLOAT NOT NULL,
	LONGITUD FLOAT NOT NULL,
	CONSTRAINT PK_SANITARIO_ECOLOGICO PRIMARY KEY (ID_SANITARIO)
);

CREATE TABLE INFRAESTRUCTURA(
	ID_INFRA INT NOT NULL,
	EQUI_URBANO VARCHAR(50) NOT NULL,
	TIPO_ACTI VARCHAR(50) NOT NULL,
	CALLE VARCHAR(50) NOT NULL,
	NUMERO VARCHAR(50) NOT NULL,
	COLONIA VARCHAR(50) NOT NULL,
	LATITUD FLOAT NOT NULL,
	LONGITUD FLOAT NOT NULL,
	ACTIVIDAD VARCHAR(50) NOT NULL,
	FOLIO_CESAC VARCHAR(50) NOT NULL,
	PETICION_ESCRITA VARCHAR(50) NOT NULL,
	PETICION_FUNCIONARIO VARCHAR(50) NOT NULL,
	REDES_SOCIALES VARCHAR(50) NOT NULL,
	FECHA_INICIO DATE NOT NULL,
	FECHA_TERMINO DATE NOT NULL,
	AVANCE INT NOT NULL,
	FUENTE VARCHAR(50) NOT NULL,
	BANQUETA_M2 VARCHAR(50) NOT NULL,
	GUARDICION_ML VARCHAR(50) NOT NULL,
	DEMOLICION_M2 VARCHAR(50) NOT NULL,
	CIMBRADO_ML VARCHAR(50) NOT NULL,
	ALBANILERIA_M2 VARCHAR(50) NOT NULL,
	PINTURA_M2 VARCHAR(50) NOT NULL,
	MALLA_M2 VARCHAR(50) NOT NULL,
	REGISTRO_PIEZAS VARCHAR(50) NOT NULL,
	BOLARDOS_PIEZAS VARCHAR(50) NOT NULL,
	ESCOMBROS_M3 VARCHAR(50) NOT NULL,
	FUENTE_PIEZAS VARCHAR(50) NOT NULL,
	JUEGO_INFANTIL_PIEZA VARCHAR(50) NOT NULL,
	COLOR_AREA VARCHAR(50) NOT NULL,
	CONSTRAINT PK_INFRAESTRUCTURA PRIMARY KEY (ID_INFRA)
);
TRUNCATE TABLE infraestructura 
DROP TABLE USURIOS

CREATE TABLE CONTRATOS(
	ID_CONTRATO INT NOT NULL,
	DESCRIPCION VARCHAR(100) NOT NULL,
	ACTIVIDAD VARCHAR(50) NOT NULL,
	CALLE VARCHAR(50) NOT NULL,
	NUMERO VARCHAR(50) NOT NULL,
	ENTRE_CALLES VARCHAR(50) NOT NULL,
	COLONIA VARCHAR(50) NOT NULL,
	LATITUD FLOAT NOT NULL,
	LONGITUD FLOAT NOT NULL,
	CONTRATO VARCHAR(50) NOT NULL,
	RECURSOS_PROYECTO VARCHAR(10) NOT NULL,
	ORIGEN_INFORMACION VARCHAR(50) NOT NULL,
	FECHA_INICIO DATE NOT NULL,
	FECHA_TERMINO DATE NOT NULL,
	AVANCE VARCHAR(50) NOT NULL,
	CARPETA_M2 VARCHAR(50) NULL,
	BOLARDOS_PZA VARCHAR(50) NULL,
	REVO_VELOCIDAD VARCHAR(50) NULL,
	BANQUETAS_M2 VARCHAR(50) NULL,
	LUMINARIA_PZA VARCHAR(50) NULL,
	IMPERMEABILIZACION_M2 VARCHAR(50) NULL,
	PINTURA_M2 VARCHAR(50) NULL,
	INSTALACION_HIDRAULICA VARCHAR(50) NULL,
	INSTALACION_DRENAJE VARCHAR(50) NULL,
	KIT_PARQUES VARCHAR(50) NULL,
	VEGETACION_INSTALADA VARCHAR(50) NULL,
	SISTEMA_RIEGO VARCHAR(50) NULL,
	CENTRO_DEPORTIVOS VARCHAR(50) NULL,
	REHABILITACION_ESCUELAS VARCHAR(50) NULL,
	REHABILITACION_CENDI VARCHAR(50) NULL,
	REHABILITACION_TABLEROS VARCHAR(50) NULL,
	REHABILITACION_BOMBAS VARCHAR(50) NULL,
	REHABILITACION_DRENAJE VARCHAR(50) NULL,
	REHABILITACION_TECHUMBRE VARCHAR(50) NULL,
	ESTUDIOS_TECNICOS VARCHAR(50) NULL,
	RESPONSABLE_INFORMACION VARCHAR(50) NOT NULL,
	CONSTRAINT PK_CONTRATOS PRIMARY KEY (ID_CONTRATO)
);

CREATE TABLE PODA(
	ID_PODA INT NOT NULL,
	FECHA_ATENCION DATE NOT NULL,
	COLONIA VARCHAR(50) NOT NULL,
	CALLE VARCHAR(50) NOT NULL,
	NUMERO VARCHAR(50) NOT NULL,
	FOLIO VARCHAR(50) NOT NULL,
	ESPECIE VARCHAR(300) NOT NULL,
	ACLAREO_PZA INT NULL,
	DESCHUPONEO_PZA INT NULL,
	ELEVACION_DE_COPA_PZA INT NULL,
	LIB_CAMARAS_PZA INT NULL,
	LIB_FACHADA_PZA INT NULL,
	LIB_LINEAS_ELECTRICAS INT NULL,
	LIB_LUMINARIA_PZA INT NULL,
	VELA INT NULL,
	FACHADA INT NULL,
	POSTE INT NULL,
	LIB_SEMAFORO_PZA INT NULL,
	LIB_SENALAMIENTOS_PZA INT NULL,
	LIMPIEZA_COPA_PZA INT NULL,
	PODA_RESTAURACION_COPA_PZA INT NULL,
	PODA_ESTETICA_PZA INT NULL,
	PODA_MUERDAGO_PZA INT NULL,
	PODA_HENO_PZA INT NULL,
	REDUCCION_COPA_PZA INT NULL,
	TOTAL INT NOT NULL,
	LATITUD FLOAT NOT NULL,
	LONGITUD FLOAT NOT NULL,
	FUENTE_INFORMACION VARCHAR(50) NOT NULL,
	CONSTRAINT PK_PODA PRIMARY KEY (ID_PODA)
);

CREATE TABLE ESTADO(
	ID_ESTADO INT NOT NULL,
	DESCRIPCION VARCHAR(20) NOT NULL,
	CONSTRAINT PK_ESTADO PRIMARY KEY (ID_ESTADO)
);

CREATE TABLE USUARIOS(
	ID_USUARIO INT AUTO_INCREMENT PRIMARY KEY,
	NOMBRES VARCHAR(50) NOT NULL,
	AP_PATERNO VARCHAR(50) NOT NULL,
	AP_MATERNO VARCHAR(50) NOT NULL,
	CORREO VARCHAR(255) NOT NULL,
	PASSWORD VARCHAR(255) NOT NULL
);

SHOW GLOBAL VARIABLES LIKE 'local_infile';
SET GLOBAL local_infile = 1;

SELECT * FROM PODA